### ISSUE TITLE
Getting started guide: integrate dropunit in my project

### ISSUE THREAD

**Issue by renevanderark** [hhazewinkel/dropunit#1]
Is it possible to write a quick start guide documenting how to quickly integrate dropunit in my project?

I see quite some potential, but without a more detailed usage guide, the learning curve for reusing my own non-generic mock servers is still a lot less steep.

**Comment by hhazewinkel** [comment]
This is planned soon.

**Comment by hhazewinkel** [comment]
A README.md is added that explains the way to continue develop of DropUnit, the method to use it in a project its integration testing and the integration-testing setup including Docker can be used as example
